version: "2"
linters:
  default: fast
  disable:
    - depguard
formatters:
  enable:
    - goimports
    - gofmt
    - gofumpt
  settings:
    goimports:
      local-prefixes:
        - go-template
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
